# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='antonyms',
        ),
        migrations.RemoveField(
            model_name='word',
            name='synonyms',
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.ManyToManyField(to='dictionary.Word'),
        ),
    ]
